### ISSUE TITLE
how to set data source on condition based in nested sections 

### ISSUE THREAD

**Issue by saukif** [jobsta/reportbro-designer#108]
Suppose This is my data
`Lines[{'Quantity':5000,'BrokerAgreements':[{'Name':'abc'},{'Name':'xyz'}]},{'Quantity':10000,'BrokerAgreements':[]}]`

i have a situation where i am using a section and data source for it is ${Lines}. and inside this section i place a table and set its data source as ${BrokerAgreements}. and then i print it. but it only print single line  not this one `{'Amount':10000,'BrokerAgreements':[]}`
![Screenshot from 2023-12-01 15-34-49](https://github.com/jobsta/reportbro-designer/assets/140400915/98fc746f-f14c-43e3-8e50-23c02b98b6f9)
 what i want is to set the data source dynamically like  `${BrokerAgreements} if len(${BrokerAgreements})>0 else ''`

**Comment by alhman** [comment]
If the table is empty then the table is not printed as there is no data. If you don't want to print the whole section content then you need to remove this line from your Lines parameter.
