### ISSUE TITLE
Designer Layers

### ISSUE THREAD

**Issue by lachlanhickey** [jobsta/reportbro-designer#11]
Are we able to set positions of parameters in relevance to them being stacked? 
Ie, can i put in a background image and have that 'Sent to back'

**Comment by alhman** [comment]
Elements are drawn in the same order as they appear in the report template (i.e. y-position). In case they have the same y-position the order in the menu panel on the left determines which element is drawn first.

**Comment by lachlanhickey** [comment]
Thanks for the reply. 

I am almost there with all my questions. Would you have a simple HTML example where it submits a raw file to the lib server and returns a report?

I have the server successfully setup, can generate the report via postman, returns a key but not sure how to submit it from a HTML form, or button. 

Any simple suggestions?

This product is amazing, by the way.

**Comment by alhman** [comment]
Not sure if I understand what you mean with "raw file", maybe the report definition? It's best to study the demo application which shows how to generate reports and how to design and directly test them. e.g. in albums/templates/albums/report/edit.html the designer is instantiated and uses the run controller in report_views.py for report preview.

**Comment by lachlanhickey** [comment]
Also, I am getting an 'invalid page size' error (attempting to have a receipt at 80mm wide)

**Comment by alhman** [comment]
The page format drop down cannot be changed. If you don't want to use predefined settings then you have to define your own dimensions. Currently there is a limit for minimum of 100mm width, we'll change it to a lower value in the next version.

**Comment by alhman** [comment]
Minimum page width is now reduced (30mm)
