### ISSUE TITLE
Preview failed : Adding more information about error

### ISSUE THREAD

**Issue by mterceno** [jobsta/reportbro-designer#111]
Hello,

Do you think it would be possible to add more information when there's an error in the preview?
I encountered an error that took me a long time to resolve. I solved it by debugging the preview run. 

I think it's in this part of this code. It would be interesting to mention the exception information in the message or in the console. 

![image](https://github.com/jobsta/reportbro-designer/assets/4966754/3a519463-393a-42ed-ac39-f4a53e3b32ba)

Best regards,

**Comment by alhman** [comment]
You can always go to the Developer Console in the Browser and view the actual request response data in the network tab. Please post the response and if possible a report json file to reproduce the error. Usually the error should be handled in the Designer with an appropriate mesage.

**Comment by mterceno** [comment]
It's not really related to the report but rather to the implementation. I indicated a property in the header (ioiReportName) without encoded value with the encodeURIComponent method.

I recently had a value containing a UTF8 character => an exception was thrown => Preview failed

![image](https://github.com/jobsta/reportbro-designer/assets/4966754/b7b942db-a1b2-46fc-ba73-f67cc16b740f)

https://github.com/jobsta/reportbro-designer/assets/4966754/97c1614e-0117-40e3-9aa9-8ca8ca6dfaab


I also cannot report an error from the backend to the frontend in designer mode.
![image](https://github.com/jobsta/reportbro-designer/assets/4966754/dd2736be-c588-46fd-a535-ed59d11787f9)

An exception is raised with a clear error message but is not reported on the frontend => Only "Preview failed". In the console / Network, I have the details of the exception but it is not clearly displayed for the end user. Should I format the http response to show an error?

**Comment by alhman** [comment]
Why should it be displayed to the end user when this is an error on your backend only relevant for developers? As a developer one of the first things in such a case is always to check the actual network response data.

If you really want to show the error in the designer you can use the same response format as used for other errors (you need to specify an existing object id and field so it can be displayed).

**Comment by mterceno** [comment]
Yes, it is true that in good practice, this is what should be done. 

We have implemented our own variable structures that allow us to search for data from different modules of our application.
Before printing a report on the backend side, we look for our variable structure in the dataset to convert them when possible. Sometimes, the user does not respect our variable structure and we would like to report this problem to him.

OK, I'll try to use the same answer format. Thank you for your advice

**Comment by alhman** [comment]
to show error details in the document properties you can use this response:
```{"errors": [{"msg_key": "error details...", "object_id": "0_document_properties", "field": "pageFormat", "info": null, "context": null}]}```
this will work in the next release (currently the error id for this field is not set).
