### ISSUE TITLE
activate menuband "save"

### ISSUE THREAD

**Issue by bitblitz4use** [jobsta/reportbro-designer#112]
Thanks for the great work you have done with this repo.

But I am still struggling with a few things, mostly the guides on the website explain how to convert the report definition along with the data into a pdf or xls. 
However, what I have not figured out yet is how to activate the save button in the menu band to save the report definition I just designed as a file or db entry via ajax post for example.

**Comment by alhman** [comment]
When the report is changed in the designer the save button is automatically enabled. You can also manually change enbaled/disabled status with API method [setModified](https://www.reportbro.com/framework/api#designer-methods) as well as triggering the `save` method - depending on what you want to accomplish.
