### ISSUE TITLE
Save design

### ISSUE THREAD

**Issue by anuj9196** [jobsta/reportbro-designer#114]
Have set up the QR code designer with the following code
```html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="{% static 'plugins/pdf-designer/dist/reportbro.css' %}"/>
    <script src="{% static 'plugins/pdf-designer/dist/reportbro.js' %}"></script>
</head>
<body>
<div id="report-bro"></div>

<script type="text/javascript">
    const rb = new ReportBro(document.getElementById('report-bro'));
</script>
</body>
</html>
```

How can I save the design and use it with the Python library (Django)?

<img width="1680" alt="Screenshot 2024-04-14 at 2 39 36 PM" src="https://github.com/jobsta/reportbro-designer/assets/6560085/6cc3af0f-f1c0-4fc1-8df3-62f7f848185d">

**Comment by mariarauch** [comment]
You have to implement the saveCallback
Take a look at the demo app which contains detailed explanation:
https://www.reportbro.com/framework/demo
