### ISSUE TITLE
the name of the downloaded xlsx file

### ISSUE THREAD

**Issue by alboret** [jobsta/reportbro-designer#120]
the name of the downloaded xls file like ab533d8f-7ce4-4785-9d0b-5bf8a6c356dd.xlsx and not informative

http header in response
`Content-Disposition: inline; filename="report-2024-06-07 16:19:22.403269.xlsx"`

just a minor inconvenience

**Comment by alhman** [comment]
The xlsx download is only for preview to test if the template works. The filename must be unique (therefor it contains the timestamp) but otherwise this is not important as the xlsx should not be used anyway.
