### ISSUE TITLE
Copy and Paste lose position, relative to document and relative another object

### ISSUE THREAD

**Issue by scorninpc** [jobsta/reportbro-designer#126]
Hii! I'm testing reportbro again, because it's proving to be a fantastic tool. I'm using the latest release, but when I copy and paste an object, it loses its position and returns 0x0. Even if I copy 2 or 3 objects, they all go to 0x0 when I paste. Is this some configuration I'm doing wrong?

https://github.com/user-attachments/assets/d1ed5383-6d35-4321-96ab-3dc6c2c20338

**Comment by alhman** [comment]
This is a desired behavior. A copied element must usually be positioned, if the element is at the same position it cannot be distinguished from the original one. Therefor the element goes to 0, 0

**Comment by scorninpc** [comment]
I Understand. But as another visual editors, this cannot be +10 px top, +10px left, for example?

When we got 3 or 4 pages, its alot hard to push elements to down
