### ISSUE TITLE
Multi-rows table header and merge cells

### ISSUE THREAD

**Issue by nvn01234** [jobsta/reportbro-designer#13]
I need multi-rows table header and merge cells to customize the table layout. Did you develope these features? I hope they will be developed :D 
Thank you

**Comment by alhman** [comment]
This is currently not possible. You can increase the header size, align text to the top and write text in header cells with multiple lines.

**Comment by gaofeiyss** [comment]
When do you update a cell merge？

**Comment by gaofeiyss** [comment]
Thank you

**Comment by alhman** [comment]
Cell merge (colspan) is now supported
