### ISSUE TITLE
how pass queryset to report?

### ISSUE THREAD

**Issue by himalsaman** [jobsta/reportbro-designer#16]
if I want pass django model one or more and use him attributes as parameters in report designer
e.g:
```
class Employee(models.Model):
    class Meta:
        db_table = 'hr_employee'
    id = models.IntegerField(db_column='id', primary_key=True)
    name = models.CharField(db_column='name', max_length=100)
    civil_id = models.CharField(db_column='civil_id', max_length=20)
    job = models.ForeignKey(Job, db_column='job', on_delete=models.DO_NOTHING)
```

```
class Job(models.Model):
    class Meta:
        managed = False
        db_table = '[Toyor_Aljanna].[dbo].[hr_jobs]'

    id = models.IntegerField(db_column='id', primary_key=True)
    name = models.CharField(db_column='name', max_length=100)
    job_type = models.IntegerField(db_column='job_type')

```

I want make report for employee with them job so I want pass employee model to report and add attributes in report as parameters.

Thanks

**Comment by alhman** [comment]
You need to convert the models to python data types, in your case a list of dicts with one entry for each employee. The dict contains the name (str), id (int) and so on. The same is basically done in the demo application https://www.reportbro.com/docs/setup
