### ISSUE TITLE
About the album application in Setup running locally

### ISSUE THREAD

**Issue by FreeDom401** [jobsta/reportbro-designer#18]
In the Settings inside the album application is running locally, I added Chinese in the album page to print error
![image](https://user-images.githubusercontent.com/45120459/56105836-d5d51c00-5f70-11e9-9480-77e17d831554.png)
![image](https://user-images.githubusercontent.com/45120459/56105853-ee453680-5f70-11e9-9736-14c3ce747d90.png)
But I can print the Chinese font in the report page
![image](https://user-images.githubusercontent.com/45120459/56105893-25b3e300-5f71-11e9-956e-f985b933443f.png)
So I would like to ask how to set the font of the album page

**Comment by alhman** [comment]
Please post questions in our support group at
https://groups.google.com/forum/?fromgroups#!forum/reportbro

The report preview uses the run method in report_views.py, so you have already added the additional font to this ReportBro instance. The report with your album data is generated in the report method in album_views.py. Therefor you also need to set the additional font for this instance.

**Comment by FreeDom401** [comment]
Thank you very much for your help, but I added the Chinese font, but I still reported an error. Should I modify the default font in the source code?

**Comment by alhman** [comment]
Did you set your font in all text elements which can contain Chinese text? maybe you forgot to set it at least for one element. In the preview only the title contains Chinese characters but not the table cells.

If you need to find out which element causes the error you can use the browser debugging tools and look for the div with id rbro_el_content_text22 (object_id is available in the report error object)
