### ISSUE TITLE
how to use firefly bold font

### ISSUE THREAD

**Issue by IvanLiu1102** [jobsta/reportbro-designer#19]
i want to use the firefly bold font, but it only have regular firefly font, i cant find the firefly bold font,please answer me how to use it

**Comment by alhman** [comment]
Please post questions in our support group at
https://groups.google.com/forum/?fromgroups#!forum/reportbro

I assume you have already setup the additional font. The additional_fonts parameter for the ReportBro instance takes a dict for each new font. Beside the filename property you can also specify bold_filename to reference the file which is used for bold text. see
https://www.reportbro.com/docs/methods#reportbro-lib
for a description of the parameter
