### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by phrbarbosa** [jobsta/reportbro-designer#2]
Hello,

Do you have specific internationalization files in your code?
I have interest in translating it to pt-BR (Portuguese/Brazil)

Best regards!
Pedro

**Comment by applibs** [comment]
There is many locale strings and change it by initialization is not good.
Can you make very simple function which will paste it by file?
for example:
$("#reportbro").reportBro({ i18n: /lang/br.js });
Its not much hard to do it. Please do it, it will be very usefull for many users.

**Comment by alhman** [comment]
There are now separate language files available (en-us and de-de already included)
