### ISSUE TITLE
How to render a table within a table

### ISSUE THREAD

**Issue by ravsom** [jobsta/reportbro-designer#20]
Is there a way to render a table within a table?

1. I wasn't able to add a table widget into a table cell
1. Wasn't able to select an array within an array on to a table's datasource

**Comment by alhman** [comment]
Please post such questions in our group:
https://groups.google.com/forum/?fromgroups#!forum/reportbro

A table only supports text data. If you need more advanced options you can use sections, e.g. you can print a table inside a section.
