### ISSUE TITLE
npm package almost empty for version 1.2.0

### ISSUE THREAD

**Issue by alfupe** [jobsta/reportbro-designer#23]
It's me or there exists any problem installing the npm package? This is what I get after a `npm install reportbro-designer`
![image](https://user-images.githubusercontent.com/6408433/61468345-64e13e00-a97d-11e9-8edc-297fd18f8c05.png)

Thanks!

**Comment by alhman** [comment]
We have fixed the npm package in version 1.2.1

**Comment by alfupe** [comment]
Thanks!
