### ISSUE TITLE
Demo django app doesn't handle images

### ISSUE THREAD

**Issue by ryancausey** [jobsta/reportbro-designer#26]
I was testing this out using the django demo app and when I added an image to the report and saved everything seemed to stop working. My best guess is that the data isn't being saved as valid JSON. Interestingly the preview works, but after saving the report you cannot download an album report nor does the edit report page load properly after navigating away and then navigating back.

### Steps to reproduce
1. Follow steps on https://www.reportbro.com/docs/setup to get django demo app running
2. Go to http://localhost:8000/albums/report/edit/
3. Add an image somewhere in the report
4. Save the report
5. Go to http://localhost:8000/albums/album/index/
6. Download a album report
7. Navigate back to http://localhost:8000/albums/report/edit/

### Expected behavior
1. Report displays as PDF with image (Step 6 above)
2. Can edit the report again (Step 7 above)

### Actual behavior
1. Returns error string: "report exception: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"
2. Report is blank (I.E. missing all previously configured information)

**Comment by alhman** [comment]
The problem is that the report is not saved correctly in the django demo app. In albums/report_views.py the report definition must be converted to json in the save controller. e.g. 
```
report_definition = json.dumps(dict(
        docElements=json_data.get('docElements'), styles=json_data.get('styles'),
        parameters=json_data.get('parameters'),
        documentProperties=json_data.get('documentProperties'), version=json_data.get('version')))
```
