### ISSUE TITLE
Resize handlers in table elements

### ISSUE THREAD

**Issue by alfupe** [jobsta/reportbro-designer#27]
Hi there!

Is there a way to hide the resize handlers on the Table Elements? Since the way to resize a table is through each column itself and not through the corner handlers it's a bit confusing to the user.

Thanks!

**Comment by alhman** [comment]
This will be fixed in the next release. While we still show the markers in the table corners (to indicate that the table is selected), the move-cursor is shown instead of the resize-cursor.

**Comment by alfupe** [comment]
Thanks!

**Comment by alhman** [comment]
fixed in latest release 1.3.3
