### ISSUE TITLE
Preserve styling properties after selecting style none

### ISSUE THREAD

**Issue by alfupe** [jobsta/reportbro-designer#28]
Hi!

Let's say we have a custom style but would like to make a little override on text align but want to preserve the other properties like font weight or color, etc. To be able to change the align we would need to select "none" in the Style dropdown but doing this we will lose all the other properties and our element would be reset to default styles :-(.

Is there a way to add overrides over an element with a style applied? if not, would be great to preserve the styles once we select "none" in the Style dropdown.

A little gif to illustrate:
![apply-styles](https://user-images.githubusercontent.com/6408433/67204813-9ea76200-f40e-11e9-8c90-12e94635d5c5.gif)

Thanks!

**Comment by alhman** [comment]
Automatically overriding all properties when changing the style to none is not a good idea. This would probably be rather confusing. Maybe this could be done with an own action button (copy properties from selected style) but I'm not sure if it would be that useful.

You could already do the following: copy & paste the style (select, then Ctr+C, Ctr+V) and then adapt the new style (e.g. change text align).

**Comment by alfupe** [comment]
Oops, ok! Thanks a lot for answering. In our case we cannot copy&paste since we have the #rbroMainPanel completely hidden to the user. So I think we would need to style the tables and other generated objects without styles. Let's see.

Thanks a lot!

**Comment by alhman** [comment]
good news: since we completely rewrote the properties panel (you can now edit multiple elements at once) we could also improve the handling of style properties. When a style is selected all style properties are still visible and set according to the selected style. Then you can modify the style properties to your needs (the style link will be unset).

**Comment by alhman** [comment]
@alfupe I'll close this bug, let me know in case you have any questions.

**Comment by alfupe** [comment]
@alhman super good news! it's a very nice improvement! thanks a lot!
