### ISSUE TITLE
Alternate Background Color in table cell with applied style

### ISSUE THREAD

**Issue by alfupe** [jobsta/reportbro-designer#29]
Hi!

When trying to use **Alternate Background Color** in a table we will not see alternating color in those **cells with an applied style** (no matter if they have background color or not) meanwhile the cells without style are working fine.

An image just to illustrate:
![alternate-background](https://user-images.githubusercontent.com/6408433/67278023-65332d00-f4c8-11e9-8ccf-8ae2488d5ac0.png)

Thanks!

**Comment by alhman** [comment]
Hi,

thanks for pointing this out. This bug will be fixed in the next release.

btw, this i a rendering issue - therefor should be reported to https://github.com/jobsta/reportbro-lib instead. You can leave this issue here since we already fixed it (just to let you know for future bug reports).

**Comment by alfupe** [comment]
Great! and so sorry for reporting this here.

**Comment by alhman** [comment]
was moved to reportbro-lib
