### ISSUE TITLE
Group data within tables

### ISSUE THREAD

**Issue by rjschave** [jobsta/reportbro-designer#3]
Does this project support grouping data within the tables by data source parameters?

I noticed that if I select the content element within a table, group expression is a setting.  I haven't figured out what to do with this and didn't see this mentioned in the documentation.

![reportbro_group_expression](https://user-images.githubusercontent.com/11916949/46911982-4191ea00-cf38-11e8-8f24-9450cd1d6922.png)

I frequently need to group data within a report.  Ideally, group would have headers (for titles) and footers (for aggregating data).

**Comment by mariarauch** [comment]
To use grouping you need to add another content row in the table settings and define the group expression on the content row. 
I've added the grouping functionality to the delivery slip demo: [](https://www.reportbro.com/demos/deliveryslip) https://www.reportbro.com/demos/deliveryslip
In the example I group table data based on DeliveryItems.Category and print the category name as header.
You may add a grouping footer too by adding another content row.

@rjschave Thanks for the hint to the missing documentation, I'll update it.

**Comment by rjschave** [comment]
I was able to add a content row for the group footer.  I'd like to sub-total at the group level, but haven't been able to figure out how to implement that.

I tried using "${Delivery.ShippingWeight} kg" in the content row for the group footer (same value as in the table footer), but I get the total for all categories, not the totals for that specific category.

I'm looking to achieve something like this:

![screen shot 2019-01-25 at 12 39 12 pm](https://user-images.githubusercontent.com/11916949/51762956-2db16480-209f-11e9-8572-076dbca3df00.png)

But, instead I'm getting this:

![screen shot 2019-01-25 at 12 47 17 pm](https://user-images.githubusercontent.com/11916949/51763004-63eee400-209f-11e9-889a-8f7421c8a6d9.png)

Is aggregation at the group level supported?

**Comment by arisobel** [comment]
I have the same demannd
It would increase a lot for this incredible Tool

**Comment by alhman** [comment]
aggregation at the group level is possible but you have to calculate the sub-group sums yourself and store it along your other row data.

the table has two content rows, and one row has a group expression set. This row is only
printed when the group expression changes.

To show group sums create a parameter list, e.g. with the following fields
"name", "group", "price", "group_price"

test data could look like
"apple", "fruits", 2, 2
"orange", "fruits", 3, 5
"banana", "fruits", 2, 7
"tomato", "vegetables", 3, 3
"potato", "vegetables", 1, 4
"salad", "vegetables", 2, 6

so the last value is the current group sum, when the group changes this value will be used (-> group_price for fruits is 7, group_price for vegetables is 6)

create a table with 2 content rows, the last content row has the group expression set for ${group} and in the row cell you can print the ${group_price}
