### ISSUE TITLE
Issue with Text overlaps when Print conditions are applied

### ISSUE THREAD

**Issue by ravsom** [jobsta/reportbro-designer#31]
As this seemed like a bug - I thought it appropriate to raise one

- Add two tables with Print conditions. I have used:  ${InvoiceDetails.InvoiceAmountGross} < 3000 for one table and ${InvoiceDetails.InvoiceAmountGross} >= 3000 for the other

![image](https://user-images.githubusercontent.com/3941526/67757521-f757aa00-fa61-11e9-821e-74c9a8794bd5.png)

- If the table content is overflowing to next page, then the content of text box overlaps with table content

![image](https://user-images.githubusercontent.com/3941526/67757493-ea3abb00-fa61-11e9-90d5-d6e3c00e1c6c.png)

[Also put up in the forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/reportbro/-mbewFZ_y6o)

**Comment by alhman** [comment]
You're right, this is a bug. It is a rendering issue (therefor should be reported to https://github.com/jobsta/reportbro-lib instead) which we will fix with the next release.
