### ISSUE TITLE
Add ability to change table height

### ISSUE THREAD

**Issue by Waguilar33** [jobsta/reportbro-designer#33]
Is it possible to add the ability to change a cells height in a table?

**Comment by alhman** [comment]
You must select the table row (e.g. by clicking on the "Content" entry in the outline on the left side) and enter the minimum height in the properties.

**Comment by Waguilar33** [comment]
> You must select the table row (e.g. by clicking on the "Content" entry in the outline on the left side) and enter the minimum height in the properties.

Thank you @alhman the working of the property got me confused. However, when the size of the font is very little. The table cell is way to big for it content.

![Screen Shot 2019-11-18 at 09 50 50](https://user-images.githubusercontent.com/21320293/69067638-04c0de00-09e9-11ea-9a83-8b755b610892.png)

This leaves the report with no space.

**Comment by alhman** [comment]
I don't understand what's the issue here. Just change the row height or cell width according to your needs. Same as with table row you can select a cell in the outline (or by double click on the cell) and then set its width.

**Comment by Waguilar33** [comment]
Am I missing something? How can you change the row height? @alhman

**Comment by alhman** [comment]
![Screenshot from 2019-11-18 17-13-40](https://user-images.githubusercontent.com/23240822/69069513-e083f200-0a26-11ea-993a-593e81b5536d.png)

as mentioned above, select the row in the outline ('Content' element is selected as you can see in the screenshot) and then set the height (selected input field in the properties)

**Comment by Waguilar33** [comment]
My god I completely missed that... Thank you very much @alhman. You sir deserve a cookie.

**Comment by alhman** [comment]
great :)
