### ISSUE TITLE
styled parameter

### ISSUE THREAD

**Issue by saglamhkn** [jobsta/reportbro-designer#36]
Hello, 

Is there any way or easy workaround to make a parameter in static text bold, italic etc.
For example:

Hello ${CustomerName}. This document .....

How can I give different style to CustomerName. I can try something with different text nodes combined in a frame but length of customer name is unknown.

**Comment by mariarauch** [comment]
Hi, There is no rich text editor and hence no possibility to use different text styling within one text element.

**Comment by alhman** [comment]
We recently released version 2.0.0 which features rich text support (only available in PLUS version). Rich text can be seen in action in the certificate demo:
https://www.reportbro.com/demo/certificate
