### ISSUE TITLE
Run command callback on docElement selection

### ISSUE THREAD

**Issue by alfupe** [jobsta/reportbro-designer#38]
Hi!

Do you think it would be easy to allow run a callback when a doc Element is selected in canvas? We would love to know at least the id of the selected docElement.

For the moment we will implement an alternative based in MutationObserver when any `rbroDocElement` node gets a class `rbroSelected` and then looking for its id in `reportBro.selections` array or something similar.

Thanks!

**Comment by alhman** [comment]
Hi,

we will add a callback which is called when an object is selected (or deselected) in the next version. The callback gets the object so you can use the id, name or whatever you need.

**Comment by alfupe** [comment]
Thanks a lot!

**Comment by alhman** [comment]
the callback is now available in the latest release 1.4.0
