### ISSUE TITLE
Render text as hyperlink

### ISSUE THREAD

**Issue by rjschave** [jobsta/reportbro-designer#4]
Is there a way to render a hyperlink that is clickable in the PDF output?

I often want to have links in reports that open the relevant record in the Django app.  They hyperlinks would need to be dynamic based on the data (e.g. row in table).

**Comment by mariarauch** [comment]
That's not possible yet but certainly a good idea. We'll try to add it to our next release.

**Comment by mariarauch** [comment]
@rjschave We have added links for text and images to the latest release. You can set the link in the print settings which also takes parameters.
You can find a working [demo](https://www.reportbro.com/demos/contract) on the website.
