### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by 4t4nner** [jobsta/reportbro-designer#41]
From example web2py app:

If I print some non english words in text field, get error `Text contains non printable character` when generate report

Tested from FF,Google chrome (80.0.3987.149) 

```python
# ~/.local/lib/python2.7/site-packages/reportbro/reportbro.py
self.set_doc_option('core_fonts_encoding', 'windows-1252')

...
# ~/.local/lib/python2.7/site-packages/reportbro/elements.py
# content is u'\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a' = 'Заголовок' (RU) in utf-8, i think
lines = pdf_doc.multi_cell(available_width, 0, content, align=self.used_style.text_align, split_only=True)

...
# ~/.local/lib/python2.7/site-packages/fpdf/fpdf.py
# self.core_fonts_encoding = windows1251 
encoded_chars = c.encode(self.core_fonts_encoding)

...
# and we got UnicodeEncodeError at ~/.local/lib/python2.7/site-packages/reportbro/elements.py:295
```

If i try `c.encode(u'utf-8')` it works normally
The same if define
```
self.set_doc_option('core_fonts_encoding', 'utf-8')
```

**Comment by alhman** [comment]
What do mean by 'it works'? If I set the encoding to utf-8 as you mentioned:
```self.set_doc_option('core_fonts_encoding', 'utf-8')```
then the text is encoded to utf-8 and the utf-8 bytes are printed. If I use the text from your example 'Заголовок' and print it with utf-8 encoding this is the result: 
![Screenshot_2020-04-03 ReportBro Demo](https://user-images.githubusercontent.com/23240822/78381754-1ab8ef00-75d6-11ea-8327-abb55f7928f2.png)

So there is no error during report generation but the result is not correct. Please post a patch in case you made more changes than the above.

I'd recommend to use a custom font which contains Russian characters. With a custom font all used characters will be embedded into the pdf so you can be sure it will work everywhere. See the [FAQ section](https://www.reportbro.com/support/index) how to add additional fonts.

**Comment by 4t4nner** [comment]
Thanks. I saw this error later.
I will try custom font.
