### ISSUE TITLE
Image Source not recognised unless ending with file extension

### ISSUE THREAD

**Issue by lachlanhickey** [jobsta/reportbro-designer#43]
I am having an issue where I need some parameters to be appended to the URL of the image source, to ensure caching expiration, etc, however 'parameter not found' error is presented where a GET variable is appended to the image source. 

Removing the GET parameter does get around this issue, however.

**Comment by alhman** [comment]
This is currently a known limitation. We'll improve this so you'll be able to use query parameters in the next version.

**Comment by alhman** [comment]
query parameters in image url are now supported in latest release 1.4.0
