### ISSUE TITLE
Report Bro Parameters "preview failed" error ==> outputFormat parameter missing or invalid

### ISSUE THREAD

**Issue by AmiraBA4** [jobsta/reportbro-designer#45]
Hello i'm working with reportBro in my angular project, i retrieved the data from my application into testData but whenever i click on preview i get "preview failed" error

that's what i wrote in my ts file
this.reportBro = $('#reportbro').reportBro(reportBroParameters);
where reportBroParameters contains all the report parameters.
I don't know what other code to add to make my preview button works

Help me plz

**Comment by alhman** [comment]
Which reportbro server are you using? As the error message indicates the parameter outputFormat is missing or invalid, outputFormat must get a value 'pdf' or 'xlsx'. If you did not modify the designer and are using the preview function then this parameter is set automatically. You should check the network requests in the Browser Developer Tools.
