### ISSUE TITLE
Support for HTML in Text element

### ISSUE THREAD

**Issue by vijaywm** [jobsta/reportbro-designer#48]
Is it possible to render Text content as HTML. I have a use case where the form field is HTML input by user. e.g.
```
<div>
     <h1>Company Name</h1>
</div>
 ```

**Comment by mariarauch** [comment]
ReportBro currently doesn't support HTML rendering but we can put it on our roadmap in case of rising demand. 
Can you elaborate your use case and give more details?

**Comment by vijaywm** [comment]
We use a py framework [Erpnext](https://erpnext.org),  that already has a feature for creating custom Print Formats (highly limited in capability compared to ReportBro! ).. where user can add html for header, footer, or body.. it renders to html using jinja and then to pdf using wkhtmltopdf..but very difficult to create a complex layout and get it right for wkhtmltopdf and manage things like repeating headers, footers etc..
Plugging in reportbro is really easy and everything else works perfect, 
If the custom html from user input could be rendered into a textbox, can let end user create letterheads etc using the existing framework features.

![image](https://user-images.githubusercontent.com/4676890/91431180-a4b36e00-e87d-11ea-9f34-c1a65bdb50d2.png)

**Comment by krajicj** [comment]
I would also appreciate this feature. This is the last thing, which I need and I will buy the unlimited licence. Good work 👍

**Comment by alhman** [comment]
The next release will support rich text content for text elements. There will be a rich text editor to create the text content. I assume this should be sufficient, right?

**Comment by alhman** [comment]
We recently released version 2.0 which features rich text support (only available in PLUS version). Rich text can be seen in action in the certificate demo:
https://www.reportbro.com/demo/certificate
