### ISSUE TITLE
about pdf print

### ISSUE THREAD

**Issue by 18428** [jobsta/reportbro-designer#5]
Hi, reportbro is great. But if you print pdf, you actually call the browser's print control, which feels bad, because there are many steps to operate. In printing, will you develop your own printing?

**Comment by alhman** [comment]
Hi, I'm not sure I understand what you mean. How should we develop our own printing? ReportBro is generating a pdf file which is displayed in the browser. Therefor the browser's print control is used when you print the document. You could just save the pdf file and then print it with any program you have installed if you don't like the browser print dialog - although I don't understand why, it's just a dialog where you press the print button.
