### ISSUE TITLE
Text contains non printable character

### ISSUE THREAD

**Issue by webasoo** [jobsta/reportbro-designer#52]
hi, I tried to use Arabic characters. but But this error is displayed to me.
plz help me!

**Comment by mariarauch** [comment]
Basically, the standard fonts included in ReportBro don't support all characters. In case of e.g. Chinese characters, an additional font can be added to ReportBro (see https://www.reportbro.com/doc/api#lib-additional_fonts and https://www.reportbro.com/doc/api#configuration-additionalFonts how to).

However, that doesn't help in your case as ReportBro doesn't support support Khmer, Tai, Arabic languages and Right-to-left printing. In some languages there is no 1:1 mapping between unicode codepoints (text content) and font glyphs, e.g. there can be multiple codepoints rendered as a single glyph. The fpdf library which we use for pdf rendering does not support this. Therefore, also ReportBro doesn't support such languages for the time being. 
See issue #37
