### ISSUE TITLE
preview failed error

### ISSUE THREAD

**Issue by ChetanAmrao** [jobsta/reportbro-designer#54]
I followed the github steps given [here](https://github.com/jobsta/reportbro-designer)
npm install then npm run build-prod

my page gives an error when I click preview

**Comment by alhman** [comment]
which version are you using? what is the error message?

the failed preview could have 2 reasons:
1. you defined a reportServerUrl for a server which is not running.
-> make sure you have no reportServerUrl set when initializing the Designer, then our public report server will be used.
2. there is an error with your report template
-> reduce the report template until report generation works to find out what's causing the error
