### ISSUE TITLE
Support for Authorization or request options

### ISSUE THREAD

**Issue by ferretwithaberet** [jobsta/reportbro-designer#55]
In case the user sets the `reportServerUrl`, let him also set something like `requestOptions` or `authorization` in case the endpoints implemented by the user require the `Authorization` header.

**Comment by alhman** [comment]
We'll add an option for the authorization header in the next release.

**Comment by alhman** [comment]
This is now available in our latest release 2.0.0 with the settings `reportServerBasicAuth` and `reportServerHeaders`.
