### ISSUE TITLE
Add processErrors function to the API

### ISSUE THREAD

**Issue by krajicj** [jobsta/reportbro-designer#56]
Is it possible to add processErrors function to the API? 

I would like to call this function to set errors returned from the reportBro Lib. I do not want to show preview to validate my report. I am creating preview while saving the report and if errors are returned from the server I would like to pass them to the designer.

Thank you for your work!

**Comment by alhman** [comment]
Yes, we can do that. The function will be added to the public API with the next release.

**Comment by krajicj** [comment]
Great! Thank you.
