### ISSUE TITLE
Feature request : rotate elements

### ISSUE THREAD

**Issue by LouisAmon** [jobsta/reportbro-designer#59]
Hi,

I noticed it's not currently possible to rotate elements (+- 90°), do you plan on adding the feature at some point ?

We do need it for barcode rotation for some logistics label templates (e.g. UPS)

**Comment by alhman** [comment]
Hi,

we have no plans in general to rotate elements as the use cases are limited. If it's only about rotation for barcode we will have a look at it and see if we can add it in a future release.

**Comment by alhman** [comment]
Rotated barcodes are now available in v3.2.0
