### ISSUE TITLE
Uncaught TypeError: data.substr is not a function

### ISSUE THREAD

**Issue by Leuan12** [jobsta/reportbro-designer#62]
An error occurred while previewing

**Comment by mariarauch** [comment]
We need more details of the report definition in order to provide help. You can retrieve the report definition in the debug mode (see tutorial here https://www.reportbro.com/guide/view/6/debug-mode).

**Comment by Leuan12** [comment]
OK, thank you. This problem has been solved

New problems

The font has been specified at the time of output, but it still prompts that there is no font under this path

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\opt\\melody\\addons_ melody14\\fireflysung\\

I try to create a new path to print correctly

But there is no one on the server. I want to ask for help

**Comment by mariarauch** [comment]
You also need to add the font to the reportbro-lib.
Read the guide here: https://www.reportbro.com/guide/view/11/fonts
