### ISSUE TITLE
reportServerHeaders option should accept an object or a function

### ISSUE THREAD

**Issue by ferretwithaberet** [jobsta/reportbro-designer#63]
The `reportServerHeaders` option should take a map containing `header: value` pairs(which it already does) or a function which returns a map containing `header: value`. In my use-case I want to put a token from [Keycloak](https://www.keycloak.org/), the token changes it's value over time, so I need to somehow update the `reportServerHeaders`.

**Comment by alhman** [comment]
We added a `requestCallback` parameter in version 2.0.1 - this function is called before a preview request and there you can update all request parameters.

**Comment by ferretwithaberet** [comment]
Thank you! I am unsure if I can test it now, as far as I remember my project at work moved away from ReportBro(The migration was not because of this issue).
