### ISSUE TITLE
requestServerHeaders is not used for the GET request

### ISSUE THREAD

**Issue by ferretwithaberet** [jobsta/reportbro-designer#64]
It is used for the `PUT` request, but not for the `GET` request.

**Comment by alhman** [comment]
The `GET` request is performed by the embedded object for pdf preview, therefore we cannot set any headers for this request.

**Comment by alhman** [comment]
In case there are custom headers we now use an ajax request and then set the embedded object manually. This has some drawbacks, e.g. filename for pdf cannot be set (which is shown in some browsers and used for download) but at least it works. Therefore the ajax request is only used when necessary (when custom headers are present).

**Comment by ferretwithaberet** [comment]
> e.g. filename for pdf cannot be set

I did not look thoroughly at the code, but cannot this be fixed by using [`XMLHttpRequest.getResponseHeader`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader) to get the [`Content-Disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) header in the `onreadystatechange` event? Might also be possible to use the [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) object instead of `Blob`.

**Comment by alhman** [comment]
We are creating the pdf object with `URL.createObjectURL` but there is no way to set the filename (at least not in a reliable way which works across all browsers). Since this is only used with custom headers and only affects the filename I think this is a minor inconvenience which can be neglected.
