### ISSUE TITLE
initialization failed

### ISSUE THREAD

**Issue by Leuan12** [jobsta/reportbro-designer#66]
When entering the page, sometimes initialization fails and the page cannot be displayed

**Comment by Leuan12** [comment]
* jQuery JavaScript Library v3.3.1

Is that the problem?

**Comment by Leuan12** [comment]
The problem has been found: it is because it is not automatically destroyed

When you enter the page again, initialization fails

How to manually call destroy?

**Comment by alhman** [comment]
just call the `destroy` method on the reportbro instance. See also public API methods:
https://www.reportbro.com/doc/api#designer-methods

If you delete the ReportBro element then you have to delete the instance as well.
