### ISSUE TITLE
Filter for data

### ISSUE THREAD

**Issue by GlauberF** [jobsta/reportbro-designer#69]
Firstly, congratulations on your work.
I'm trying to generate reports, but I came across something that I would need that I understand to be “basic”, which is filtering values that I want to be assigned.
Example, I want to make a report of products sold in 30 days, so I want the report to only show products sold from 12/01/2021 to 12/30/2021.

How would I do this filter through the editor?
Or how should I do it?

**Comment by alhman** [comment]
You can filter elements in a table row by specifying a "Print If" condition (in print settings of the table content row).

In general it is recommended to filter the data in advance (e.g. on the server where you collect your products) and then only pass the data you actually want to print to reportbro.

**Comment by GlauberF** [comment]
thanks.
