### ISSUE TITLE
Custom ReportPro

### ISSUE THREAD

**Issue by applibs** [jobsta/reportbro-designer#7]
Please how to disable Settings, I dont want them there?
Pattern locale
Pattern currency symbol

How to disable "Preview report" top button?

How to make custom function which will fire after event onChange anything? I mean when anything is changed it will be saved into some place in DOM.

**Comment by applibs** [comment]
I tried change simulate change event like this:
```
updateMenuButtons() {
        $('#rbro_menu_save').prop('disabled', (this.commandStack.length === 0 || !this.modified));
        $('#rbro_menu_undo').prop('disabled', (this.lastCommandIndex < 0));
        $('#rbro_menu_redo').prop('disabled', (this.lastCommandIndex >= (this.commandStack.length - 1)));

        if(this.modified) {
            this.save();
        }
    }
```
but its saving many many times.

**Comment by alhman** [comment]
"Maximum call stack size exceeded" is usually caused by an endless recursion, which is quite obvious in your case (updateMenuButtons -> save -> updateMenuButtons...).
If you don't want or need certain settings you can hide the dom node for the row (or just ignore settings you don't need).

**Comment by applibs** [comment]
So where to call:

```
if(this.modified) {
            this.save();
        }
```
?

**Comment by applibs** [comment]
:-(

**Comment by alhman** [comment]
We will add a callback which gets called whenever a command was executed. There you will be able to perform your autosave after each change (or every n-th change etc.).
