### ISSUE TITLE
Repeat the same Barcode multiple times on the page.

### ISSUE THREAD

**Issue by GlauberF** [jobsta/reportbro-designer#70]
I have to generate a report to print several labels (Barcode with name and code) for a certain product.
How can I do this without having to drag the Barcode component into the report several times and set the parameters again.

**Comment by alhman** [comment]
In case you only print a single product you can use sections to iterate through a list of Barcodes. Otherwise you'd have to use multiple Barcode components (as nested sections are currently not supported).

**Comment by GlauberF** [comment]
I would have an example template for this scenario, where I want to print multiple codes for a single product.

**Comment by alhman** [comment]
https://gist.github.com/alhman/27c5406a81eea49199321b1f22f8adef
