### ISSUE TITLE
Table grouping is truncated

### ISSUE THREAD

**Issue by myrae69** [jobsta/reportbro-designer#78]
First of all thank you for that great package that saved me hours of work.
There is just something strange that might be a bug or I maybe can't seem to adjust the settings correctly :

![image](https://user-images.githubusercontent.com/3015589/172783223-d5cc33b4-0b7b-4fe0-aa35-3d3b9c6d504f.png)
We can see here that the blue row from table grouping disapear from the page. It does the same for the average row and the "space between groups" row. However it seems that it doesn't happen when it is a simple table row.
I tried many things to make it work like deleting header, footer, margins, or tweaking different settings like the  "Always on same page" but it doesn't work.

Thank you for your help.

Regards

**Comment by alhman** [comment]
This is a bug when rendering a table group after page break. Fixed with the latest release of reportbro-lib v2.1.1

**Comment by myrae69** [comment]
Thank you very much it works now. I thought pip got me the last version but it was 2.1.0.

Regards
