### ISSUE TITLE
dynamic sheet height for thermal printers.

### ISSUE THREAD

**Issue by GlauberF** [jobsta/reportbro-designer#82]
I'm creating, through the editor, a print model that will come out in the thermal printers, but I need the height to be dynamic, according to the items.

example below.
![Captura de Tela_selecionar área_20220715162606](https://user-images.githubusercontent.com/11314585/179296527-3c01e6c7-f7b8-4b7d-bb00-d32f88482403.png)

**Comment by mariarauch** [comment]
In case you use a table for the content items the content height is always dynamic whereas content items following the table keep the set distance to the above table (see e.g. the table containing the items in the invoice demo https://www.reportbro.com/demo/invoice).

You may also use a frame to reserve the space for the content items and apply the print setting "shrink to content height" to adjust its height according to the contained items (see e.g. the recipient address frame in this demo https://www.reportbro.com/demo/delivery_slip)
