### ISSUE TITLE
Create proper example for react integration with repobro-designer

### ISSUE THREAD

**Issue by sksoft22** [jobsta/reportbro-designer#87]
Please share working proper react js example for reportbro designer.

**Comment by alhman** [comment]
If you're familiar with react it should be easy to integrate reportbro. You need to have a div element and then initialize reportbro once the div is rendered:
`new ReportBro(document.getElementById('reportbro'));`

I guess you'd usually call this in the `componentDidMount` method:
https://reactjs.org/docs/react-component.html#componentdidmount
