### ISSUE TITLE
Textarea of panel not back initial height

### ISSUE THREAD

**Issue by scorninpc** [jobsta/reportbro-designer#89]
Hello

I'm reporting a visual problem, that happens when Text element has to much text, so textarea will expand. But when you select another Text element with less text, the textarea not update height, look:

![Peek 16-11-2022 09-54](https://user-images.githubusercontent.com/2607849/202186900-1af286c5-e27a-4b65-bab7-b9e2131aad78.gif)

My workaround for this, and working:

```
let rb = new ReportBro(document.getElementById('reportbro'), {
	selectCallback: function(object) {
		/**
		 * Fix text height
		 */
		$('#rbro_doc_element_content').css('height', 'initial');
		$('#rbro_doc_element_content').get(0).style.height = $('#rbro_doc_element_content').get(0).scrollHeight + 'px';
	}
});
```

Thank you for this nice project

**Comment by alhman** [comment]
This is a css issue which is resolved in master branch (commit 1ecb0bcc2bb236fbcdd3953dfef39d4a90f01384) and will be fixed in next release.
