### ISSUE TITLE
patternAdditionalDates date format always shows time

### ISSUE THREAD

**Issue by JakLiao** [jobsta/reportbro-designer#9]
`patternAdditionalDates: [
            {name: 'yyyy/MM/dd', description: 'selfPatternDate1'}
        ],`
I only want to show date, but preview will show time '2019-01-01 00:00:00'. 
What should I do to make  time disappear.

**Comment by mariarauch** [comment]
By default dates are printed as date and time. Therefore, for each date you also need to apply the pattern you want to use. E.g. in case you are using a parameter of type date select the desired print pattern in the parameter definition. Your `patternAdditionalDates` are shown in addition to the predefined patternDates in the pattern selection.
Have a look at the invoice demo (https://www.reportbro.com/demos/invoice) and configuration of the parameter `InvoiceDate` (part of the InvoiceDetails collection).
