### ISSUE TITLE
Group Calculations

### ISSUE THREAD

**Issue by AmadouTejan** [jobsta/reportbro-designer#91]
Hello 

I am using ReportBro to Generate reports.

I am grouping by Region and Village. **Motu** is a region which has a village "Makefu" and **Tafiti** is also region with its villages "Avatele" and "Tamakautoga". I want to be Summing base on the Village and Region. 

In Village "Makefu" 3 people were paid 1,000 each which sum up to 3,000 and The Grand Total for the Region **MOTU** should sum up to 3,000.

In Village "Avatele"  one person was paid 1,000 and  in "Tamakautoga" two people were paid 1,000 each which should sum up to 2,000. The Grand Total for the Region **TAFITI** should be 3,000 (adding up the 2 villages).
This Table below is exactly what i want to do.
<img width="437" alt="Conso" src="https://user-images.githubusercontent.com/116084781/202793154-72000d37-ccd2-44b0-b2a6-54df5afe17ee.png">

But using the Groupby and sum expression this is what my report is generating. It is grouping it by Village but it is picking only one amount(I want to calculate everything and return it here) and the Grand total is not summing base on Region but its taking the entire amount and returning it on both Regions 

This is what i have when i generate my report
<img width="473" alt="repCOn" src="https://user-images.githubusercontent.com/116084781/202796627-d8da205d-7773-4618-9f1d-f23d8295a7df.png">

Is there anyway i will be able to have it exactly like the first picture.

**Comment by alhman** [comment]
Without knowing what your report looks like I can only guess. In case you use a parameter of type "Sum" for the salary field and use this parameter in a table group row then the value will show the sum for the current group. For this to work you need reportbro-lib >= 2.1.0

In case you provide the group sum as part of your data then you are responsible for the group values. This is described in the table group guide (which was written before v2.1.0):
https://www.reportbro.com/guide/view/5/table-grouping
