### ISSUE TITLE
need vertical line in designer and preview.

### ISSUE THREAD

**Issue by SaravananArunagiri** [jobsta/reportbro-designer#94]
for our case, we may needed the vertical line to place in the report now only can see the horizontal line

As per below screenshot, looking for the line option

![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/11039629/217132453-24075955-d9e9-4dc1-bfbf-2c6baa0644c0.png)

**Comment by alhman** [comment]
We currently only support horizontal lines. What is the purpose of the vertical line? Should it have a fixed length? Most elements can expand vertically, a separate line next to such an element would not expand in that case.

**Comment by alhman** [comment]
I close this one since it seems like you found a solution. In general you should use element borders when you need vertical lines for an element.
