### ISSUE TITLE
A List inside a Collection can't be used as a data source for tables or Sections

### ISSUE THREAD

**Issue by sakibyousuf** [jobsta/reportbro-designer#97]
I have a Collection named "Address" which has a few fields and a List named "Contacts". Each contact can have a few fields. I add a table and give it the data source $Address.Contacts. Then I can't assign the Contact prameters to columns. The list is empty.

**Comment by alhman** [comment]
This is a bug in case the list is inside a collection. We will fix it in the next release. This is only an issue for the popup window, rendering still works. i.e. you can manullay enter your parameter fields in the column text in the meantime.
