### ISSUE TITLE
Inability to Distinguish Between Same Parameter Names from Different Data Sources

### ISSUE THREAD

**Issue by sakibyousuf** [jobsta/reportbro-designer#99]
Hello,

I would like to raise an issue I encountered while using your library. I am facing a problem when trying to display data from two different lists, "Loading_Address" and "Unloading_Address," in a table.

Here's the scenario: I have created a list called "Loading_Address" with fields "Product," "Country," "State," and "Code." Additionally, I have another list named "Unloading_Address" with fields "Country," "State," and "Code." To display this data in a table, I followed the steps below:

Created a section and assigned the data source to "Unloading_Address."
Added a table with three columns within the section.
Set the data source for the table to "Loading_Address."
Assigned the columns as follows:
1. First column: "Loading_Address${Product}"
2. Second column: "Loading_Address${Country}"
3. Third column: "Unloading_Address${Country}"
However, the issue arises when I try to display the "Country" data from both lists in the second and third columns of the table. The table is not able to distinguish between the two data sources, resulting in the same country being displayed in both columns.

I believe there might be a conflict or ambiguity in referencing the data sources correctly. I have provided test data with two rows in the "Loading_Address" list and one row in the "Unloading_Address" list.

Could you please provide guidance on how to properly configure the table columns to display the respective "Country" data from the "Loading_Address" and "Unloading_Address" lists?

Thank you for your attention to this matter. I appreciate your assistance in resolving this issue.
![Screenshot from 2023-07-14 00-17-42](https://github.com/jobsta/reportbro-designer/assets/22131381/a6415a6f-a06a-4566-937a-d8be9d273617)
![Screenshot from 2023-07-14 00-19-33](https://github.com/jobsta/reportbro-designer/assets/22131381/edfc16fa-688e-4411-8118-cc8f12f2af60)

**Comment by alhman** [comment]
currently there is no way to access a specific field from the parent data source. You can use different field names for the two lists as a workaround (e.g. add a prefix `LA_` and `UA_` to all fields).

**Comment by saukif** [comment]
Thanks for addressing the multiple data sources issue!

However, the issues with collections and simple parameters still persist. Your help with these would be much appreciated.
![Screenshot from 2023-09-21 17-58-09](https://github.com/jobsta/reportbro-designer/assets/140400915/15a1a7ba-a194-46f1-a617-bde59bdd8cb6)
i have the Amount Parameter outside the Invoice list and i want to use that Amount parameter on the section. it is not able to distinguish which Amount are to be printed on the pdf and same with the Customfields.name. can we have something  like ':'  to address the parameters from the root

**Comment by sakibyousuf** [comment]
Thanks for addressing the multiple data sources issue!

However, the issues with collections and simple parameters still persist. Your help with these would be much appreciated.
![Screenshot from 2023-09-21 17-58-09](https://github.com/jobsta/reportbro-designer/assets/140400915/15a1a7ba-a194-46f1-a617-bde59bdd8cb6)
i have the Amount Parameter outside the Invoice list and i want to use that Amount parameter on the section. it is not able to distinguish which Amount are to be printed on the pdf and same with the Customfields.name. can we have something  like ':'  to address the parameters from the root

**Comment by alhman** [comment]
for now I'd recommend to rename your root parameter(s), e.g. `Total_Amount` so you can reference them inside the section and avoid duplicate names.

**Comment by alhman** [comment]
root parameters are now explicitly referenced in v3.5.0
